library(ggplot2)
library(reshape)
a<-read.table("map_stat_exonic.xls",sep = "\t", head=T)
#b<-melt(a,id.vars = "sample",variable.name = "type",value.name = "reads")
b<-melt(a,id.vars = "sample")
colnames(b)<-c("sample","type","reads")
pdf(file = "exonic_barplot.pdf",width = 8,height = 8)
ggplot(b,aes(sample,reads,fill=factor(b$type,levels = c("Unmapped","Mapped.non.exonic","Mapped.exonic"))))+ theme_bw() +coord_flip() + geom_bar(stat="identity",position="fill")  +  theme(legend.position = "top") +  theme(legend.title=element_blank()) + guides(fill = guide_legend(reverse=TRUE)) + scale_fill_manual(values=c("#A9A9A9", "#FFAA01", "#00C5F0"),labels=c("Unmapped", "Mapped non-exonic", "Mapped exonic")) + theme(legend.text = element_text(size = 15)) + theme(panel.grid =element_blank())  +  ylab("Pecent of sequence reads") + theme(axis.title.x = element_text(size = 15)) +xlab("") + theme(axis.text= element_text(size = 14))
dev.off()
